### ISSUE TITLE
Invalid token

### ISSUE THREAD

**Issue by MastoryMd5** [MrMicky-FR/CraftStats#2]
Hello there,
I've currently deployed CraftStats but seems like that the SERVERS_EDIT_TOKEN var is not working properly.

![image](https://github.com/MrMicky-FR/CraftStats/assets/17986972/db0ad580-6362-427a-8041-4f28e9d1b893)

It's passed as a variable while deploying but when you try to use the token in /editor it says
`An error occurred: invalid_token`

**Comment by MrMicky-FR** [comment]
Thanks! Fixed in the above commit
